import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`box-border ${inter.className}`}>
        <div className="flex justify-center">
          
          {/* Side Bar */}
          <header className="p-6 pt-16 w-44 h-screen">
            <ul>
              <li className="font-bold mb-1">nickbrodeur.xyz / ncale.eth</li>
              <li><Link href="/">home</Link></li>
              <li><Link href="projects">projects</Link></li>
            </ul>
          </header>  
              
          {/* Main Content */}
          <div className="w-7/12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
