import type { Metadata } from "next";
import Link from "next/link";
import { Nunito } from "next/font/google";
import "./globals.css";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`box-border ${inter.className}`}>
        <div className="flex justify-center bg-white">
          
          {/* Side Bar */}
          <header className="pt-16 w-40 h-screen">
            <div className="bg-green-200 p-4 pt-3 rounded">
              <ul>
                <li className="font-bold mb-1">nickbrodeur.xyz / ncale.eth</li>
                <li><Link href="/">home</Link></li>
                <li><Link href="projects">projects</Link></li>
              </ul>
            </div>
          </header>  
              
          {/* Main Content */}
          <div className="rounded w-8/12">
            {children}
          </div>
          
        </div>
      </body>
    </html>
  );
}
